object Versions {
    const val CORE_KTX = "1.7.0"
    const val JUNIT4 = "4.13.2"
    const val ESPRESSO = "3.4.0"
    const val HILT = "2.43.2"
    const val LIFECYCLE_EXTENSIONS = "2.2.0"
    const val LIFECYCLE = "2.5.1"
    const val COROUTINE = "1.6.4"
    const val APPCOMPAT = "1.5.1"
    const val MATERIAL = "1.7.0"
    const val LEAKCANARY = "2.8.1"
    const val CONSTRAINT_LAYOUT = "2.1.4"
    const val DATASTORE = "1.0.0"
    const val PROTOBUF = "3.19.4"
    const val NAVIGATION= "2.5.3"
    const val FRAGMENT_KTX = "1.5.4"
    const val GLIDE = "4.12.0"
    const val OPENCSV = "4.4"
    const val LOTTIE = "5.2.0"
    const val SWIPE_REFRESH_LAYOUT = "1.1.0"
    const val SPLASH_SCREEN = "1.0.0"
    const val RETROFIT = "2.9.0"
    const val GSON = "2.9.0"
    const val OKHTTP_INTERCEPTOR = "4.9.1"
    const val ROOM = "2.4.3"
}